spring.datasource.url=jdbc:postgresql://ep-bold-voice-b4lxn2em-pooler.c-6.us-east-2.aws.neon.tech/portfolio-db?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_1z8rmajQOwbt


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080